### ISSUE TITLE
Manage Releases

### ISSUE THREAD

**Issue by dok42** [dok42/Hack-dok42#3]
I was going to draft a release but, before that, I thought to delete the release archives in my fork repo.. because those contains the original Hack.. right ? Can I delete those releases or I'm doing it wrong ? 

@chrissimpkins

**Comment by chrissimpkins** [comment]
Yes you can remove all previous releases of Hack in this repo and begin a new set of releases with the Hack Dok versions.  You may need to remove the git tags in order to eliminate them from Github.  I believe that the releases are automated with tags in the git history.

**Comment by dok42** [comment]
Perfect, I did remove previous releases. Thx

**Comment by chrissimpkins** [comment]
:+1:
